// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFgT1hQhGXYb7twp-uMq5Ntio00Bx94Ns',
    appId: '1:53910571719:web:1a7091320579bbecd64ce2',
    messagingSenderId: '53910571719',
    projectId: 'gym-leveling',
    authDomain: 'gym-leveling.firebaseapp.com',
    storageBucket: 'gym-leveling.firebasestorage.app',
    measurementId: 'G-WQB3P1T3XL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoBysYXQI_ikQBjHs-NfH1NvyDWYN2_7A',
    appId: '1:53910571719:android:392065a41abb5672d64ce2',
    messagingSenderId: '53910571719',
    projectId: 'gym-leveling',
    storageBucket: 'gym-leveling.firebasestorage.app',
  );
}
